services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  AIContentAuditBundle\Controller\:
    resource: '../../Controller/'
  AIContentAuditBundle\DataFixtures\:
    resource: '../../DataFixtures/'
  AIContentAuditBundle\Repository\:
    resource: '../../Repository/'
  AIContentAuditBundle\Service\:
    resource: '../../Service/'
